# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.12.3

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install ruff tox  # you can also use tox
    - pip install --editable ".[test]"
    - tox -e py,ruff


deploy_backend:
  stage: deploy
  image: python:3.12.3
  before_script:
    - python --version ; pip --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - export PATH="$CI_PROJECT_DIR/venv/bin:$PATH"
    - curl -sL https://railway.app/install.sh | sh
    - export PATH="$HOME/.railway/bin:$PATH"
  script:
    - export GOOGLE_API_KEY=$GOOGLE_API_KEY
    - export CX_KEY=$CX_KEY
    - railway up --service="backend" -d
  # only:
  #   - main


deploy_frontend:
  stage: deploy
  image: node:20
  before_script:
    - apt-get update && apt-get install -y curl bash
    - curl -sL https://railway.app/install.sh | sh
    - export PATH="$HOME/.railway/bin:$PATH"
    - railway --version
   # - railway whoami
    - cd frontend
    - npm install
    - npm run build -- --configuration production
  script:
    - railway up --service=$FRONTEND_SERVICE_ID -d




  # only:
  #   - main


run:
  script:
    - pip install .
    # run the command here
  artifacts:
    paths:
      - build/*
